// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/coopnorge/interview-backend/internal/logistics"
	"github.com/coopnorge/interview-backend/internal/logistics/config"
	"github.com/coopnorge/interview-backend/internal/logistics/services/client"
	"github.com/coopnorge/interview-backend/internal/logistics/services/operator"
)

// Injectors from wire.go:

// newWire create new DI
func newWire(cfg *config.ClientAppConfig) (*internal.ServiceInstance, func(), error) {
	apiLogisticsClient := client.NewLogisticsClient(cfg)
	worldOperator := operator.NewWorldOperator()
	serviceInstance, err := internal.NewServiceInstance(apiLogisticsClient, worldOperator, cfg)
	if err != nil {
		return nil, nil, err
	}
	return serviceInstance, func() {
	}, nil
}
